# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67261a046ffddcb7573ab0338364a0eb3ae9ba62981982bc0b90113f15c26e3843f2de7642d2415a50122f64d25c933e421e7f813e9ccb98cfe6de3c615e0b1a

test:
  secret_key_base: be91887a559f3f96bfc924c5aa86a855cabc7601000e0a609236a7350e1d6872e63412bff755ef0bc566b195f538ef6b32af8c4618e923a741ef11db6a8001fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
